var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,e,d){b instanceof String&&(b=String(b));for(var a=b.length,c=0;c<a;c++){var f=b[c];if(e.call(d,f,c,b))return{i:c,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,d){b!=Array.prototype&&b!=Object.prototype&&(b[e]=d.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,e,d,a){if(e){d=$jscomp.global;b=b.split(".");for(a=0;a<b.length-1;a++){var c=b[a];c in d||(d[c]={});d=d[c]}b=b[b.length-1];a=d[b];e=e(a);e!=a&&null!=e&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,d){return $jscomp.findInternal(this,b,d).v}},"es6","es3");
!function(b){var e=function(a,b){this.init(a,b)};e.prototype={constructor:e,init:function(a,c){a=this.$element=b(a);this.options=b.extend({},b.fn.checkbox.defaults,c);a.before(this.options.template);this.setState()},setState:function(){var a=this.$element,b=a.closest(".checkbox");a.prop("disabled")&&b.addClass("disabled");a.prop("checked")&&b.addClass("checked")},toggle:function(){var a=this.$element,c=a.closest(".checkbox"),f=a.prop("checked"),e=b.Event("toggle");0==a.prop("disabled")&&(c.toggleClass("checked")&&
f?a.removeAttr("checked"):a.prop("checked","checked"),a.trigger(e).trigger("change"))},setCheck:function(a){var c=this.$element,f=c.closest(".checkbox"),e="check"==a?!0:!1;a=b.Event(a);f[e?"addClass":"removeClass"]("checked")&&e?c.prop("checked","checked"):c.removeAttr("checked");c.trigger(a).trigger("change")}};var d=b.fn.checkbox;b.fn.checkbox=function(a){return this.each(function(){var c=b(this),f=c.data("checkbox"),d=b.extend({},b.fn.checkbox.defaults,c.data(),"object"==typeof a&&a);f||c.data("checkbox",
f=new e(this,d));"toggle"==a&&f.toggle();"check"==a||"uncheck"==a?f.setCheck(a):a&&f.setState()})};b.fn.checkbox.defaults={template:'\x3cspan class\x3d"icons"\x3e\x3cspan class\x3d"first-icon fa fa-square-o"\x3e\x3c/span\x3e\x3cspan class\x3d"second-icon fa fa-check-square-o"\x3e\x3c/span\x3e\x3c/span\x3e'};b.fn.checkbox.noConflict=function(){b.fn.checkbox=d;return this};b(document).on("click.checkbox.data-api","[data-toggle^\x3dcheckbox], .checkbox",function(a){var c=b(a.target);"A"!=a.target.tagName&&
(a&&a.preventDefault()&&a.stopPropagation(),c.hasClass("checkbox")||(c=c.closest(".checkbox")),c.find(":checkbox").checkbox("toggle"))});b(function(){b('[data-toggle\x3d"checkbox"]').each(function(){b(this).checkbox()})})}(window.jQuery);
!function(b){var e=function(a,b){this.init(a,b)};e.prototype={constructor:e,init:function(a,c){a=this.$element=b(a);this.options=b.extend({},b.fn.radio.defaults,c);a.before(this.options.template);this.setState()},setState:function(){var a=this.$element,b=a.closest(".radio");a.prop("disabled")&&b.addClass("disabled");a.prop("checked")&&b.addClass("checked")},toggle:function(){var a=this.$element,c=a.prop("checked"),e=a.closest(".radio"),d=(a.closest("form").length?a.closest("form"):a.closest("body")).find(':radio[name\x3d"'+
a.attr("name")+'"]'),g=b.Event("toggle");0==a.prop("disabled")&&(d.not(a).each(function(){var a=b(this),c=b(this).closest(".radio");0==a.prop("disabled")&&c.removeClass("checked")&&a.removeAttr("checked").trigger("change")}),0==c&&e.addClass("checked")&&a.prop("checked",!0),a.trigger(g),c!==a.prop("checked")&&a.trigger("change"))},setCheck:function(a){var c=this.$element,e=c.closest(".radio"),d="check"==a?!0:!1,g=c.prop("checked"),h=(c.closest("form").length?c.closest("form"):c.closest("body")).find(':radio[name\x3d"'+
c.attr("name")+'"]');a=b.Event(a);h.not(c).each(function(){var a=b(this);b(this).closest(".radio").removeClass("checked")&&a.removeAttr("checked")});e[d?"addClass":"removeClass"]("checked")&&d?c.prop("checked","checked"):c.removeAttr("checked");c.trigger(a);g!==c.prop("checked")&&c.trigger("change")}};var d=b.fn.radio;b.fn.radio=function(a){return this.each(function(){var c=b(this),d=c.data("radio"),n=b.extend({},b.fn.radio.defaults,c.data(),"object"==typeof a&&a);d||c.data("radio",d=new e(this,n));
"toggle"==a&&d.toggle();"check"==a||"uncheck"==a?d.setCheck(a):a&&d.setState()})};b.fn.radio.defaults={template:'\x3cspan class\x3d"icons"\x3e\x3cspan class\x3d"first-icon fa fa-circle-o"\x3e\x3c/span\x3e\x3cspan class\x3d"second-icon fa fa-dot-circle-o"\x3e\x3c/span\x3e\x3c/span\x3e'};b.fn.radio.noConflict=function(){b.fn.radio=d;return this};b(document).on("click.radio.data-api","[data-toggle^\x3dradio], .radio",function(a){var c=b(a.target);a&&a.preventDefault()&&a.stopPropagation();c.hasClass("radio")||
(c=c.closest(".radio"));c.find(":radio").radio("toggle")});b(function(){b('[data-toggle\x3d"radio"]').each(function(){b(this).radio()})})}(window.jQuery);
!function(b){b.fn.bootstrapSwitch=function(e){var d={init:function(){return this.each(function(){var a=b(this),c,d="",e=a.attr("class"),g;var h="ON";var l="OFF";var k=!1;b.each(["switch-mini","switch-small","switch-large"],function(a,b){0<=e.indexOf(b)&&(d=b)});a.addClass("has-switch");void 0!==a.data("on")&&(c="switch-"+a.data("on"));void 0!==a.data("on-label")&&(h=a.data("on-label"));void 0!==a.data("off-label")&&(l=a.data("off-label"));void 0!==a.data("icon")&&(k=a.data("icon"));h=b("\x3cspan\x3e").addClass("switch-left").addClass(d).addClass(c).html(h);
c="";void 0!==a.data("off")&&(c="switch-"+a.data("off"));c=b("\x3cspan\x3e").addClass("switch-right").addClass(d).addClass(c).html(l);l=b("\x3clabel\x3e").html("\x26nbsp;").addClass(d).attr("for",a.find("input").attr("id"));k&&l.html('\x3ci class\x3d"'+k+'"\x3e\x3c/i\x3e');k=a.find(":checkbox").wrap(b("\x3cdiv\x3e")).parent().data("animated",!1);!1!==a.data("animated")&&k.addClass("switch-animate").data("animated",!0);k.append(h).append(l).append(c);a.find("\x3ediv").addClass(a.find("input").is(":checked")?
"switch-on":"switch-off");a.find("input").is(":disabled")&&b(this).addClass("deactivate");var m=function(a){a.siblings("label").trigger("mousedown").trigger("mouseup").trigger("click")};a.on("keydown",function(a){32===a.keyCode&&(a.stopImmediatePropagation(),a.preventDefault(),m(b(a.target).find("span:first")))});h.on("click",function(a){m(b(this))});c.on("click",function(a){m(b(this))});a.find("input").on("change",function(a){var c=b(this),d=c.parent(),e=c.is(":checked"),f=d.is(".switch-off");a.preventDefault();
d.css("left","");f===e&&(e?d.removeClass("switch-off").addClass("switch-on"):d.removeClass("switch-on").addClass("switch-off"),!1!==d.data("animated")&&d.addClass("switch-animate"),d.parent().trigger("switch-change",{el:c,value:e}))});a.find("label").on("mousedown touchstart",function(a){var c=b(this);g=!1;a.preventDefault();a.stopImmediatePropagation();c.closest("div").removeClass("switch-animate");c.closest(".has-switch").is(".deactivate")?c.unbind("click"):(c.on("mousemove touchmove",function(a){var c=
b(this).closest(".switch");a=((a.pageX||a.originalEvent.targetTouches[0].pageX)-c.offset().left)/c.width()*100;g=!0;25>a?a=25:75<a&&(a=75);c.find("\x3ediv").css("left",a-75+"%")}),c.on("click touchend",function(a){var c=b(this),d=b(a.target).siblings("input");a.stopImmediatePropagation();a.preventDefault();c.unbind("mouseleave");g?d.prop("checked",!(-25>parseInt(c.parent().css("left")))):d.prop("checked",!d.is(":checked"));g=!1;d.trigger("change")}),c.on("mouseleave",function(a){var c=b(this),d=c.siblings("input");
a.preventDefault();a.stopImmediatePropagation();c.unbind("mouseleave");c.trigger("mouseup");d.prop("checked",!(-25>parseInt(c.parent().css("left")))).trigger("change")}),c.on("mouseup",function(a){a.stopImmediatePropagation();a.preventDefault();b(this).unbind("mousemove")}))})})},toggleActivation:function(){b(this).toggleClass("deactivate")},isActive:function(){return!b(this).hasClass("deactivate")},setActive:function(a){a?b(this).removeClass("deactivate"):b(this).addClass("deactivate")},toggleState:function(a){var c=
b(this).find("input:checkbox");c.prop("checked",!c.is(":checked")).trigger("change",a)},setState:function(a,c){b(this).find("input:checkbox").prop("checked",a).trigger("change",c)},status:function(){return b(this).find("input:checkbox").is(":checked")},destroy:function(){var a=b(this).find("div");a.find(":not(input:checkbox)").remove();a=a.children();a.unwrap().unwrap();a.unbind("change");return a}};if(d[e])return d[e].apply(this,Array.prototype.slice.call(arguments,1));if("object"!==typeof e&&e)b.error("Method "+
e+" does not exist!");else return d.init.apply(this,arguments)}}(jQuery);